FROM <%= config[:namespaced_path] %>_api

ENV XN_CLIENT   <%= config[:name] %>
ENV XN_ENV      production
ENV PACER_MANUAL_JARS true
#ENV XN_BKP_GPG_EMAIL  ...

# Use the dev image, but freshly copy in the app code since
# it may have changed since the dev image was created.
COPY . /app

# Bundle in deployment mode
RUN ruby --dev bundle install --deployment --path $VENDOR_BUNDLE
