#!/bin/bash

# Returns the revision number used for deployment.

set -e

# This command relies on the existance of a v0.0 tag at the position we
# start counting from (preferably the first commit)
REVISION=`git --no-replace-objects describe --tags --match v0.0`

# Extract the number of commits in the repo.
REVISION=${REVISION:5} # drop the first 5 characters

echo v$(script/version).$REVISION

