#!/bin/sh

### BEGIN INIT INFO
# Provides:		xnlogic
# Required-Start:	$docker
# Required-Stop:	$docker
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Boots app build on the XN Framework
### END INIT INFO

# This assumes you have created an xnlogic user, added the user to the docker
# group (ie. sudo usermod -aG docker xnlogic), and placed your 
# docker-compose.yml file in that user's home directory.

set -e

PROJECT_NAME=xnlogic
YAMLFILE=/home/$PROJECT_NAME/docker-compose.yml
OPTS="-f $YAMLFILE -p $PROJECT_NAME"
UPOPTS="-d"

case "$1" in
    start)
        echo "Starting Docker Compose" "dockercompose"
        /usr/local/bin/docker-compose $OPTS up $UPOPTS
        ;;

    stop)
        echo "Stopping Docker Compose" "dockercompose"
        /usr/local/bin/docker-compose $OPTS stop
        ;;

    reload)
        echo "Reloading Docker Compose" "dockercompose"
        /usr/local/bin/docker-compose $OPTS up $UPOPTS
        ;;

    restart)
        /usr/local/bin/docker-compose $OPTS stop
        /usr/local/bin/docker-compose $OPTS up $UPOPTS
        ;;

    *)
        echo "Usage: /etc/init.d/dockercompose {start|stop|restart|reload}"
        exit 1
        ;;
esac

exit 0
